# Generated by Django 3.1.2 on 2021-08-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0002_picture_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='images',
            new_name='image',
        ),
    ]
